### ISSUE TITLE
Error when executing nested JavaScript commands

### ISSUE THREAD

**Issue by Natrium729** [vorple/vorple#34] opened 2018-08-22 20:52 UTC
The following crashed the interpreter:

```inform 7
To decide what text is id of (O - an object):
    execute JavaScript command "'[O]'.split(' ').join('_').toLowerCase();"; [1]
    decide on the text returned by the JavaScript command.

When play begins:
    execute JavaScript command "'Hello [id of some object] World'"; [2]
    say "[text returned by the JavaScript command].".
```

In the second JavaScript command, I use `id of (object)`, which in turn execute another JavaScript command.

The error is:

```
JavaScript from story file threw an error: "" string literal contains an unescaped line break
```
And if I display the faulty code, as explained in #33, I get:

```
"Hello 
*** Error on file 'VpJSEval': tried to open a file already open ***

*** Run-time problem P48: Error handling external file.


*** Error on file 'VpJSEval': only closed files can be marked ***
Vorple Test World"
```

("Vorple Test" is the name of the Inform project.)

So it seems that Inform throws a Runtime problem concerning the opening of the file. I can't explain why, though. I thought the steps Inform went through were:

1. On line [2], Inform has to substitute the text `"'Hello [id of some object] World'"`.
2. Inform executes the JavaScript on line [1] and decide on the text returned by the JavaScript.
3. Inform is back to line [2] and can now execute the second JavaScript command.

If Inform really did go through these steps, then there would not be any problem since the JavaScript commands are executed one after the other.

So I don't know if this issue can be solved, and if not, a note about it could be added to the documentation.

**Comment by juhana** [comment] 2018-09-02 10:32
This was caused by I7 opening the file before resolving text substitutions in the JS code, which would cause the file to be opened again if the text substitutions would try to evaluate JS code themselves. The JS code text is now substituted before the file is opened.

You can go around it in the current version with:

```
When play begins:
    let id be the substituted form of id of some object;
    execute JavaScript command "'Hello [id] World'"; 
    say "[text returned by the JavaScript command].".
```

**Closed by juhana** 2018-09-02 10:32 UTC
